### ISSUE TITLE
Evaluating transformer explainability

### ISSUE THREAD

**Issue by jaiswati** [understandable-machine-intelligence-lab/Quantus#115]
Hello @sebastian-lapuschkin ,

Thank you for the great work, 

Please suggest, is there any sample reference example, for using this framework with transformer explainability like this one
https://github.com/hila-chefer/Transformer-Explainability
& this one https://github.com/berniwal/swin-transformer-pytorch

Best Regards,
@jaiswati

**Comment by dilyabareeva** [comment]
@jaiswati Thanks for your feedback. Since the XAI method implementations you are referring to are not built into Quantus library, the best approach would be to pass your custom explanation function to metrics. Please refer to [README/Getting Started/Step 2. Load explanations/Employ customised functions](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md#getting-started) for more detail.
